services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:                 
      - ./frontend:/app 
      - /app/node_modules
    network_mode: host
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    network_mode: host
volumes:
  pgdata:
