name: Frontend com Testes

on: push

jobs:
  build-and-test:
    name: Build e Testes do Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências do frontend
        working-directory: ./frontend
        run: npm install

      - name: Rodar testes
        working-directory: ./frontend
        run: npm run lint